name: Test Video Tours
on:
  workflow_dispatch:
jobs:
  test-video-tours:
    timeout-minutes: 90
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Create env file
        run: |
          touch .env
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
      - name: Run video tours
        env:
          VIDEO_TOUR: "true"
        run: bun run video-tours
      - name: Upload videos to Cloudinary
        run: bun run upload-videos -- --force
        env:
          CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}
      - name: Commit cloudinary assets
        run: |
          git config --local user.email "$USER_EMAIL"
          git config --local user.name "$USER_NAME"
          git pull
          git add data/cloudinary_assets.json
          git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Update cloudinary assets"
        env:
          USER_EMAIL: ${{ vars.USER_EMAIL }}
          USER_NAME: ${{ vars.USER_NAME }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PUSH_TOKEN }}
          branch: main
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: videos
          path: videos/
          retention-days: 30
